# -*- coding: utf-8 -*-
"""scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17iHmx7cKR-ymh9OOEDeIBSHbHlAedN5c
"""

!apt-get update -qq
!apt-get install -y -qq libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2 libpangocairo-1.0-0 libpango-1.0-0 libcairo2 libatspi2.0-0 libnss3 libxkbcommon0
!pip install -q playwright rapidfuzz beautifulsoup4 lxml
!playwright install chromium

import asyncio
import re
import sqlite3
import json
from pathlib import Path
import pandas as pd
import numpy as np
import ipywidgets as widgets
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from playwright.async_api import async_playwright
from bs4 import BeautifulSoup
from IPython.display import display, clear_output
from rapidfuzz import fuzz, process as rfprocess
import nest_asyncio
nest_asyncio.apply()

def normalize_hs(code):
    digits = re.sub(r"\D", "", code)
    return digits if len(digits) >= 2 else None

def extract_duty_vat(cell_text):
    percentages = re.findall(r"(\d+(?:\.\d+)?)%", cell_text)
    duty = float(percentages[0]) if percentages else 0.0
    vat = float(percentages[1]) if len(percentages) > 1 else 19.0
    return duty, vat

# Commented out IPython magic to ensure Python compatibility.
# %%writefile scraper_v2.py
# import requests, time, re, json, warnings
# from pathlib import Path
# from bs4 import BeautifulSoup
# warnings.filterwarnings("ignore", message="Unverified HTTPS request")
# 
# BASE_URL = "https://www.douane.gov.tn/tarifwebnew/getresultat.php"
# CHECKPOINT_FILE = "scrape_checkpoint.json"
# SESSION = requests.Session()
# SESSION.verify = False
# CHAPTERS = [f"{i:02d}" for i in range(1, 98)]
# 
# def fetch_chapter_hs_codes(chap):
#     r = SESSION.get(BASE_URL, params={"choix": "1", "chap": chap}, timeout=30)
#     soup = BeautifulSoup(r.text, "lxml")
#     results = []
#     for table in soup.find_all("table"):
#         for tr in table.find_all("tr")[1:]:
#             cells = tr.find_all(["td","th"])
#             if len(cells) >= 2:
#                 hs_clean = re.sub(r"\D", "", cells[0].get_text(" ", strip=True))
#                 desc = cells[1].get_text(" ", strip=True)
#                 if len(hs_clean) >= 6:
#                     results.append({"hs_code": hs_clean, "description": desc[:300]})
#     return results
# 
# def fetch_hs_detail(hs_code):
#     r = SESSION.get(BASE_URL, params={"choix": "", "chap": "", "sel": hs_code}, timeout=30)
#     soup = BeautifulSoup(r.text, "lxml")
#     result = {
#         "hs_code": hs_code, "dd_rate": 0.0, "dd_assiette": "",
#         "tva_rate": 19.0, "other_taxes": [], "pref_rates": [],
#         "import_regime": "", "export_regime": "",
#     }
#     for table in soup.find_all("table"):
#         rows = table.find_all("tr")
#         if not rows:
#             continue
#         headers = [th.get_text(" ", strip=True) for th in rows[0].find_all(["td","th"])]
#         if "IMPORT" in headers and "EXPORT" in headers:
#             if len(rows) > 1:
#                 cells = rows[1].find_all(["td","th"])
#                 if len(cells) >= 2:
#                     result["import_regime"] = cells[0].get_text(" ", strip=True)
#                     result["export_regime"] = cells[1].get_text(" ", strip=True)
#         if "DROITS / TAXES" in headers and "Valeur" in headers:
#             for tr in rows[1:]:
#                 cells = tr.find_all(["td","th"])
#                 if len(cells) >= 2:
#                     tax_name = cells[0].get_text(" ", strip=True)
#                     tax_val = cells[1].get_text(" ", strip=True)
#                     assiette = cells[2].get_text(" ", strip=True) if len(cells) > 2 else ""
#                     pct = re.findall(r"(\d+(?:\.\d+)?)\s*%", tax_val)
#                     rate = float(pct[0]) if pct else None
#                     if "DD" in tax_name and "DROIT DOUANE" in tax_name:
#                         result["dd_rate"] = rate if rate is not None else 0.0
#                         result["dd_assiette"] = assiette
#                     elif "TVA" in tax_name:
#                         result["tva_rate"] = rate if rate is not None else 19.0
#                     else:
#                         result["other_taxes"].append({"name": tax_name, "value": tax_val, "assiette": assiette})
#         if "Taux Préférentiel" in headers or "Code Pays" in headers:
#             for tr in rows[1:]:
#                 cells = tr.find_all(["td","th"])
#                 if len(cells) >= 3:
#                     pct = re.findall(r"(\d+(?:\.\d+)?)\s*%", cells[2].get_text(" ", strip=True))
#                     if pct:
#                         result["pref_rates"].append({
#                             "country_code": cells[0].get_text(" ", strip=True),
#                             "country_name": cells[1].get_text(" ", strip=True),
#                             "rate": float(pct[0])
#                         })
#     return result
# 
# def scrape_full(max_chapters=None, delay=0.3):
#     chapters = CHAPTERS[:max_chapters] if max_chapters else CHAPTERS
#     print("Phase 1: collecting HS codes...")
#     all_hs, seen = [], set()
#     for chap in chapters:
#         try:
#             hs_list = fetch_chapter_hs_codes(chap)
#             for item in hs_list:
#                 if item["hs_code"] not in seen:
#                     seen.add(item["hs_code"])
#                     all_hs.append(item)
#             print(f"  Chapter {chap}: {len(hs_list)} HS codes")
#             time.sleep(delay)
#         except Exception as e:
#             print(f"  Chapter {chap} error: {e}")
#     print(f"Total unique HS codes: {len(all_hs)}")
#     print("\nPhase 2: fetching duty details...")
#     results = []
#     for i, item in enumerate(all_hs):
#         try:
#             detail = fetch_hs_detail(item["hs_code"])
#             detail["description"] = item["description"]
#             results.append(detail)
#             if (i+1) % 50 == 0:
#                 print(f"  {i+1}/{len(all_hs)} done...")
#             time.sleep(delay)
#         except Exception as e:
#             print(f"  Error on {item['hs_code']}: {e}")
#     print(f"\nDone. {len(results)} HS codes with full duty detail.")
#     return results

# Commented out IPython magic to ensure Python compatibility.
# %%writefile scraper_v3.py
# import requests, time, re, json, warnings, pickle
# from pathlib import Path
# from bs4 import BeautifulSoup
# warnings.filterwarnings("ignore", message="Unverified HTTPS request")
# 
# BASE_URL = "https://www.douane.gov.tn/tarifwebnew/getresultat.php"
# SESSION = requests.Session()
# SESSION.verify = False
# CHAPTERS = [f"{i:02d}" for i in range(1, 98)]
# PROGRESS_FILE = "scrape_progress.pkl"
# 
# def fetch_chapter_hs_codes(chap):
#     r = SESSION.get(BASE_URL, params={"choix": "1", "chap": chap}, timeout=30)
#     soup = BeautifulSoup(r.text, "lxml")
#     results = []
#     for table in soup.find_all("table"):
#         for tr in table.find_all("tr")[1:]:
#             cells = tr.find_all(["td","th"])
#             if len(cells) >= 2:
#                 hs_clean = re.sub(r"\D", "", cells[0].get_text(" ", strip=True))
#                 desc = cells[1].get_text(" ", strip=True)
#                 if len(hs_clean) >= 6:
#                     results.append({"hs_code": hs_clean, "description": desc[:300]})
#     return results
# 
# def fetch_hs_detail(hs_code, retries=3, delay=0.5):
#     for attempt in range(retries):
#         try:
#             r = SESSION.get(BASE_URL, params={"choix": "", "chap": "", "sel": hs_code}, timeout=30)
#             soup = BeautifulSoup(r.text, "lxml")
#             result = {
#                 "hs_code": hs_code, "dd_rate": 0.0, "dd_assiette": "",
#                 "tva_rate": 19.0, "other_taxes": [], "pref_rates": [],
#                 "import_regime": "", "export_regime": "",
#             }
#             for table in soup.find_all("table"):
#                 rows = table.find_all("tr")
#                 if not rows: continue
#                 headers = [th.get_text(" ", strip=True) for th in rows[0].find_all(["td","th"])]
#                 if "IMPORT" in headers and "EXPORT" in headers:
#                     if len(rows) > 1:
#                         cells = rows[1].find_all(["td","th"])
#                         if len(cells) >= 2:
#                             result["import_regime"] = cells[0].get_text(" ", strip=True)
#                             result["export_regime"] = cells[1].get_text(" ", strip=True)
#                 if "DROITS / TAXES" in headers and "Valeur" in headers:
#                     for tr in rows[1:]:
#                         cells = tr.find_all(["td","th"])
#                         if len(cells) >= 2:
#                             tax_name = cells[0].get_text(" ", strip=True)
#                             tax_val = cells[1].get_text(" ", strip=True)
#                             assiette = cells[2].get_text(" ", strip=True) if len(cells) > 2 else ""
#                             pct = re.findall(r"(\d+(?:\.\d+)?)\s*%", tax_val)
#                             rate = float(pct[0]) if pct else None
#                             if "DD" in tax_name and "DROIT DOUANE" in tax_name:
#                                 result["dd_rate"] = rate if rate is not None else 0.0
#                                 result["dd_assiette"] = assiette
#                             elif "TVA" in tax_name:
#                                 result["tva_rate"] = rate if rate is not None else 19.0
#                             else:
#                                 result["other_taxes"].append({"name": tax_name, "value": tax_val, "assiette": assiette})
#                 if "Taux Préférentiel" in headers or "Code Pays" in headers:
#                     for tr in rows[1:]:
#                         cells = tr.find_all(["td","th"])
#                         if len(cells) >= 3:
#                             pct = re.findall(r"(\d+(?:\.\d+)?)\s*%", cells[2].get_text(" ", strip=True))
#                             if pct:
#                                 result["pref_rates"].append({
#                                     "country_code": cells[0].get_text(" ", strip=True),
#                                     "country_name": cells[1].get_text(" ", strip=True),
#                                     "rate": float(pct[0])
#                                 })
#             return result
#         except Exception as e:
#             if attempt < retries - 1:
#                 time.sleep(delay * (attempt + 2))
#             else:
#                 return None
# 
# def scrape_full(max_chapters=None, delay=0.1, save_every=200):
#     chapters = CHAPTERS[:max_chapters] if max_chapters else CHAPTERS
#     results = {}
#     if Path(PROGRESS_FILE).exists():
#         with open(PROGRESS_FILE, "rb") as f:
#             results = pickle.load(f)
#         print(f"Resuming — {len(results)} HS codes already done")
#     print("Phase 1: collecting HS codes...")
#     all_hs, seen = [], set()
#     for chap in chapters:
#         try:
#             hs_list = fetch_chapter_hs_codes(chap)
#             for item in hs_list:
#                 if item["hs_code"] not in seen:
#                     seen.add(item["hs_code"])
#                     all_hs.append(item)
#             time.sleep(delay)
#         except Exception as e:
#             print(f"  Chapter {chap} error: {e}")
#     print(f"Total unique HS codes: {len(all_hs)}")
#     todo = [item for item in all_hs if item["hs_code"] not in results]
#     print(f"Phase 2: {len(todo)} remaining to fetch...")
#     for i, item in enumerate(todo):
#         detail = fetch_hs_detail(item["hs_code"], delay=delay)
#         if detail:
#             detail["description"] = item["description"]
#             results[item["hs_code"]] = detail
#         if (i+1) % save_every == 0:
#             with open(PROGRESS_FILE, "wb") as f:
#                 pickle.dump(results, f)
#             print(f"  {len(results)}/{len(all_hs)} done (saved)")
#         time.sleep(delay)
#     with open(PROGRESS_FILE, "wb") as f:
#         pickle.dump(results, f)
#     print(f"\nDone. {len(results)} HS codes total.")
#     return list(results.values())

exec(open("scraper_v3.py").read())
results_full = scrape_full(max_chapters=None, delay=0.1)

from google.colab import drive
drive.mount('/content/drive')
import shutil
shutil.copy("scrape_progress.pkl", "/content/drive/MyDrive/scrape_progress.pkl")
print("✅ Backed up to Google Drive")

from google.colab import files
files.download("scrape_progress.pkl")

results_full = scrape_full(max_chapters=None, delay=0.1)

import pickle
with open("results_full.pkl", "wb") as f:
    pickle.dump(results_full, f)
print(f"✅ Saved {len(results_full)} results to results_full.pkl")

from google.colab import drive
drive.mount('/content/drive')
import shutil
shutil.copy("results_full.pkl", "/content/drive/MyDrive/results_full.pkl")
print("✅ Backed up to Google Drive")

11550

exec(open("scraper_v2.py").read())
results = scrape_full(max_chapters=3, delay=0.3)
for r in results[:3]:
    print(f"\nHS {r['hs_code']}: {r['description'][:50]}")
    print(f"  DD={r['dd_rate']}% | TVA={r['tva_rate']}% | Pref rates: {len(r['pref_rates'])}")
    if r['pref_rates']:
        print(f"  Pref sample: {r['pref_rates'][:3]}")

# Rebuild DB with real duty data from scraper_v2
conn = sqlite3.connect("tunisia_trade.db")
cursor = conn.cursor()

cursor.execute("DROP TABLE IF EXISTS tariff_measures")
cursor.execute("""
    CREATE TABLE tariff_measures (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        hs_code TEXT,
        origin_country TEXT,
        duty_type TEXT,
        tax_type TEXT,
        rate REAL,
        agreement_name TEXT,
        measure_type TEXT,
        valid_from DATE,
        valid_to DATE,
        assiette TEXT,
        tax_name TEXT
    )
""")

cursor.execute("DROP TABLE IF EXISTS hs_details")
cursor.execute("""
    CREATE TABLE hs_details (
        hs_code TEXT PRIMARY KEY,
        description TEXT,
        import_regime TEXT,
        export_regime TEXT,
        other_taxes TEXT
    )
""")

# Country code mapping (numeric → ISO-2)
COUNTRY_CODE_MAP = {
    "818": "EG", "792": "TR", "504": "MA", "276": "DE", "250": "FR",
    "380": "IT", "724": "ES", "528": "NL", "056": "BE", "356": "IN",
    "840": "US", "392": "JP", "410": "KR", "704": "VN", "076": "BR",
    "400": "JO", "682": "SA", "784": "AE", "434": "LY", "012": "DZ",
    "788": "TN", "156": "CN", "191": "HR", "040": "AT", "620": "PT",
    "300": "GR", "752": "SE", "208": "DK", "246": "FI", "372": "IE",
    "442": "LU", "275": "PS", "760": "SY", "422": "LB", "887": "YE",
    "368": "IQ", "414": "KW", "048": "BH", "634": "QA", "512": "OM",
    "120": "CM", "480": "MU", "646": "RW", "834": "TZ", "288": "GH",
    "404": "KE",
}

inserted = 0
for r in results:
    hs = r["hs_code"]

    # MFN DD row
    cursor.execute("""
        INSERT INTO tariff_measures
        (hs_code, origin_country, duty_type, tax_type, rate, measure_type, valid_from, valid_to, assiette, tax_name)
        VALUES (?, 'TN', 'MFN', 'DD', ?, 'MFN', '2025-01-01', '2025-12-31', ?, 'DD')
    """, (hs, r["dd_rate"], r["dd_assiette"]))

    # MFN TVA row
    cursor.execute("""
        INSERT INTO tariff_measures
        (hs_code, origin_country, duty_type, tax_type, rate, measure_type, valid_from, valid_to, tax_name)
        VALUES (?, 'TN', 'MFN', 'TVA', ?, 'MFN', '2025-01-01', '2025-12-31', 'TVA')
    """, (hs, r["tva_rate"]))

    # Other taxes
    for tax in r.get("other_taxes", []):
        pct = re.findall(r"(\d+(?:\.\d+)?)\s*%", tax["value"])
        rate = float(pct[0]) if pct else None
        if rate is not None:
            cursor.execute("""
                INSERT INTO tariff_measures
                (hs_code, origin_country, duty_type, tax_type, rate, measure_type, valid_from, valid_to, assiette, tax_name)
                VALUES (?, 'TN', 'MFN', 'OTHER', ?, 'MFN', '2025-01-01', '2025-12-31', ?, ?)
            """, (hs, rate, tax["assiette"], tax["name"][:100]))

    # Preferential rates (real data from portal)
    for pref in r.get("pref_rates", []):
        iso2 = COUNTRY_CODE_MAP.get(pref["country_code"], pref["country_code"])
        cursor.execute("""
            INSERT INTO tariff_measures
            (hs_code, origin_country, duty_type, tax_type, rate, measure_type, valid_from, valid_to, tax_name)
            VALUES (?, ?, 'PREF', 'DD', ?, 'PREF', '2025-01-01', '2025-12-31', ?)
        """, (hs, iso2, pref["rate"], pref["country_name"][:100]))

    # HS details
    cursor.execute("""
        INSERT OR REPLACE INTO hs_details (hs_code, description, import_regime, export_regime, other_taxes)
        VALUES (?, ?, ?, ?, ?)
    """, (hs, r["description"], r["import_regime"], r["export_regime"],
          json.dumps(r["other_taxes"])))

    inserted += 1

conn.commit()

# Summary
cursor.execute("SELECT COUNT(*) FROM tariff_measures WHERE duty_type='MFN' AND tax_type='DD'")
mfn_count = cursor.fetchone()[0]
cursor.execute("SELECT COUNT(*) FROM tariff_measures WHERE duty_type='PREF'")
pref_count = cursor.fetchone()[0]
cursor.execute("SELECT AVG(rate) FROM tariff_measures WHERE duty_type='MFN' AND tax_type='DD' AND rate > 0")
avg_duty = cursor.fetchone()[0]

conn.close()
print(f"✅ Inserted {inserted} HS codes")
print(f"   MFN DD rows: {mfn_count}")
print(f"   PREF rows: {pref_count}")
print(f"   Average MFN duty (non-zero): {avg_duty:.1f}%")

conn = sqlite3.connect("tunisia_trade.db")
cursor = conn.cursor()
cursor.execute("""
    SELECT tm.hs_code, tm.rate as duty_rate,
           (SELECT rate FROM tariff_measures
            WHERE hs_code = tm.hs_code AND tax_type='TVA' AND duty_type='MFN' LIMIT 1) AS vat_rate,
           hd.description, hd.import_regime
    FROM tariff_measures tm
    LEFT JOIN hs_details hd ON tm.hs_code = hd.hs_code
    WHERE tm.origin_country = 'TN' AND tm.duty_type = 'MFN' AND tm.tax_type = 'DD'
    ORDER BY tm.hs_code
""")
rows = cursor.fetchall()
conn.close()

DF_HS = pd.DataFrame(rows, columns=["hs_code","duty_rate","vat_rate","description","import_regime"])
DF_HS["description"] = DF_HS["description"].fillna("")
DF_HS["search_text"] = (DF_HS["description"] + " " + DF_HS["hs_code"]).str.lower()

print(f"✅ Loaded {len(DF_HS)} HS codes")
print(f"   Non-zero duty rates: {(DF_HS['duty_rate']>0).sum()}")
print(f"   Average duty: {DF_HS[DF_HS['duty_rate']>0]['duty_rate'].mean():.1f}%")
print(DF_HS[DF_HS['duty_rate']>0][["hs_code","description","duty_rate"]].head(10))

import requests
import time
import warnings
warnings.filterwarnings("ignore", message="Unverified HTTPS request")

BASE_URL = "https://www.douane.gov.tn/tarifwebnew/getresultat.php"
CHECKPOINT_FILE = "scrape_checkpoint.json"
SESSION = requests.Session()
SESSION.verify = False

def fetch_chapter_hs_codes(chap):
    """Fetch list of HS codes for a chapter. Returns list of {hs_code, description}."""
    r = SESSION.get(BASE_URL, params={"choix": "1", "chap": chap}, timeout=30)
    soup = BeautifulSoup(r.text, "lxml")
    results = []
    for table in soup.find_all("table"):
        rows = table.find_all("tr")
        for tr in rows[1:]:  # skip header
            cells = tr.find_all(["td","th"])
            if len(cells) >= 2:
                hs = cells[0].get_text(" ", strip=True)
                desc = cells[1].get_text(" ", strip=True)
                hs_clean = re.sub(r"\D", "", hs)
                if len(hs_clean) >= 6:
                    results.append({"hs_code": hs_clean, "description": desc[:300]})
    return results

def fetch_hs_detail(hs_code):
    """Fetch full duty breakdown for one HS code. Returns dict with rates."""
    r = SESSION.get(BASE_URL, params={"choix": "", "chap": "", "sel": hs_code}, timeout=30)
    soup = BeautifulSoup(r.text, "lxml")

    result = {
        "hs_code": hs_code,
        "dd_rate": 0.0,
        "dd_assiette": "",
        "tva_rate": 19.0,
        "other_taxes": [],
        "pref_rates": [],
        "import_regime": "",
        "export_regime": "",
    }

    tables = soup.find_all("table")
    for table in tables:
        rows = table.find_all("tr")
        if not rows:
            continue
        headers = [th.get_text(" ", strip=True) for th in rows[0].find_all(["td","th"])]

        # Import/Export regime table
        if "IMPORT" in headers and "EXPORT" in headers:
            if len(rows) > 1:
                cells = rows[1].find_all(["td","th"])
                if len(cells) >= 2:
                    result["import_regime"] = cells[0].get_text(" ", strip=True)
                    result["export_regime"] = cells[1].get_text(" ", strip=True)

        # Duties table
        if "DROITS / TAXES" in headers and "Valeur" in headers:
            for tr in rows[1:]:
                cells = tr.find_all(["td","th"])
                if len(cells) >= 2:
                    tax_name = cells[0].get_text(" ", strip=True)
                    tax_val = cells[1].get_text(" ", strip=True)
                    assiette = cells[2].get_text(" ", strip=True) if len(cells) > 2 else ""

                    # Extract numeric rate
                    pct = re.findall(r"(\d+(?:\.\d+)?)\s*%", tax_val)
                    rate = float(pct[0]) if pct else None

                    if "DD" in tax_name and "DROIT DOUANE" in tax_name:
                        result["dd_rate"] = rate if rate is not None else 0.0
                        result["dd_assiette"] = assiette
                    elif "TVA" in tax_name:
                        result["tva_rate"] = rate if rate is not None else 19.0
                    else:
                        result["other_taxes"].append({
                            "name": tax_name, "value": tax_val, "assiette": assiette
                        })

        # Preferential rates table
        if "Taux Préférentiel" in headers or "Code Pays" in headers:
            for tr in rows[1:]:
                cells = tr.find_all(["td","th"])
                if len(cells) >= 3:
                    country_code = cells[0].get_text(" ", strip=True)
                    country_name = cells[1].get_text(" ", strip=True)
                    pref_val = cells[2].get_text(" ", strip=True)
                    pct = re.findall(r"(\d+(?:\.\d+)?)\s*%", pref_val)
                    pref_rate = float(pct[0]) if pct else None
                    if pref_rate is not None:
                        result["pref_rates"].append({
                            "country_code": country_code,
                            "country_name": country_name,
                            "rate": pref_rate
                        })

    return result

# CHAPTERS: 01-97
CHAPTERS = [f"{i:02d}" for i in range(1, 98)]

def scrape_full(max_chapters=None, resume=True, delay=0.5):
    start_chapter = 0
    all_hs = []

    if re

conn = sqlite3.connect("tunisia_trade.db")
cursor = conn.cursor()

cursor.execute("DROP TABLE IF EXISTS tariff_measures")
cursor.execute("""
    CREATE TABLE tariff_measures (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        hs_code TEXT,
        origin_country TEXT,
        duty_type TEXT,
        tax_type TEXT,
        rate REAL,
        agreement_name TEXT,
        measure_type TEXT,
        valid_from DATE,
        valid_to DATE,
        source_url TEXT,
        legal_basis TEXT
    )
""")

for _, row in df_mfn.iterrows():
    hs = row['hs_code']
    duty = row['duty_rate']
    vat = row['vat_rate']
    cursor.execute("""
        INSERT INTO tariff_measures (hs_code, origin_country, duty_type, tax_type, rate, measure_type, valid_from, valid_to)
        VALUES (?, 'TN', 'MFN', 'DD', ?, 'MFN', '2025-01-01', '2025-12-31')
    """, (hs, duty))
    cursor.execute("""
        INSERT INTO tariff_measures (hs_code, origin_country, duty_type, tax_type, rate, measure_type, valid_from, valid_to)
        VALUES (?, 'TN', 'MFN', 'TVA', ?, 'MFN', '2025-01-01', '2025-12-31')
    """, (hs, vat))

conn.commit()
conn.close()
print(f"✅ Inserted {len(df_mfn)} HS codes into tariff_measures ({len(df_mfn)*2} rows total).")

conn = sqlite3.connect("tunisia_trade.db")
cursor = conn.cursor()

cursor.execute("DROP TABLE IF EXISTS agreements")
cursor.execute("""
    CREATE TABLE agreements (
        id INTEGER PRIMARY KEY,
        name TEXT,
        type TEXT,
        valid_from DATE,
        valid_to DATE
    )
""")

agreements_data = [
    ("EU-Tunisia Association", "FTA", "2020-01-01", None),
    ("Turkey-Tunisia FTA", "FTA", "2010-01-01", None),
    ("Agadir Agreement", "FTA", "2007-01-01", None),
    ("PAFTA (Arab FTA)", "FTA", "1998-01-01", None),
]
for name, typ, vf, vt in agreements_data:
    cursor.execute("INSERT INTO agreements (name, type, valid_from, valid_to) VALUES (?, ?, ?, ?)",
                   (name, typ, vf, vt))

cursor.execute("DROP TABLE IF EXISTS agreement_members")
cursor.execute("""
    CREATE TABLE agreement_members (
        agreement_id INTEGER,
        origin_country TEXT,
        FOREIGN KEY(agreement_id) REFERENCES agreements(id)
    )
""")

members = {
    "EU-Tunisia Association": ["FR","DE","IT","ES","NL","BE","AT","PT","GR","SE","DK","FI","IE","LU"],
    "Turkey-Tunisia FTA": ["TR"],
    "Agadir Agreement": ["MA","EG","JO"],
    "PAFTA (Arab FTA)": ["SA","AE","LY","JO","EG","MA","DZ","PS","SY","LB","YE","IQ","KW","BH","QA","OM"]
}

agreement_ids = {}
cursor.execute("SELECT id, name FROM agreements")
for row in cursor.fetchall():
    agreement_ids[row[1]] = row[0]

for agree, countries in members.items():
    for c in countries:
        cursor.execute("INSERT INTO agreement_members (agreement_id, origin_country) VALUES (?, ?)",
                       (agreement_ids[agree], c))

cursor.execute("SELECT DISTINCT hs_code FROM tariff_measures WHERE duty_type='MFN' AND tax_type='DD'")
hs_codes = [row[0] for row in cursor.fetchall()]

for hs in hs_codes:
    for agree, countries in members.items():
        for origin in set(countries):
            cursor.execute("""
                INSERT INTO tariff_measures (hs_code, origin_country, duty_type, tax_type, rate, agreement_name, measure_type, valid_from, valid_to)
                VALUES (?, ?, 'PREF', 'DD', 0.0, ?, 'PREF', '2020-01-01', '2025-12-31')
            """, (hs, origin, agree))

conn.commit()
conn.close()
print(f"✅ Agreements and preferential rows inserted for {len(hs_codes)} HS codes.")

def get_hs_ancestors(hs_code: str):
    digits = re.sub(r"\D", "", hs_code)
    # Include the full code plus standard prefix lengths
    candidates = [digits] + [digits[:l] for l in (10, 8, 6, 4, 2) if len(digits) > l]
    # Remove duplicates while preserving order
    seen = set()
    result = []
    for c in candidates:
        if c not in seen and len(c) >= 2:
            seen.add(c)
            result.append(c)
    return result

def enumerate_paths(conn, hs_code, origin_country):
    ancestors = get_hs_ancestors(hs_code)
    if not ancestors:
        return []
    placeholders = ','.join(['?'] * len(ancestors))
    query = f"""
        SELECT hs_code, origin_country, duty_type, tax_type, rate,
               agreement_name, LENGTH(hs_code) as specificity
        FROM tariff_measures
        WHERE tax_type = 'DD'
          AND hs_code IN ({placeholders})
          AND (origin_country = ? OR origin_country = 'TN')
          AND (valid_from <= date('now') OR valid_from IS NULL)
          AND (valid_to >= date('now') OR valid_to IS NULL)
        ORDER BY
            CASE duty_type WHEN 'SUSP' THEN 0 WHEN 'PREF' THEN 1 WHEN 'QUOTA' THEN 2 ELSE 3 END,
            specificity DESC
    """
    cursor = conn.cursor()
    cursor.execute(query, ancestors + [origin_country])
    rows = cursor.fetchall()
    result = []
    for i, r in enumerate(rows):
        result.append({
            'rank': i+1,
            'hs_code': r[0],
            'origin_country': r[1],
            'duty_type': r[2],
            'rate': r[4],
            'agreement_name': r[5],
            'specificity': r[6]
        })
    return result

def resolve_duty(conn, hs_code, origin_country):
    paths = enumerate_paths(conn, hs_code, origin_country)
    if not paths:
        return {'rate': None, 'duty_type': 'NOT_FOUND'}
    return paths[0]

print("✅ Engine functions loaded.")

# What's actually in the DB?
conn = sqlite3.connect("tunisia_trade.db")
cursor = conn.cursor()
cursor.execute("""
    SELECT hs_code, rate FROM tariff_measures
    WHERE origin_country = 'TN' AND duty_type = 'MFN' AND tax_type = 'DD'
    LIMIT 20
""")
print("DB rows:")
for r in cursor.fetchall():
    print(r)

print("\ndf_mfn sample:")
print(df_mfn[["hs_code","description"]].head(20))
conn.close()

conn = sqlite3.connect("tunisia_trade.db")
cursor = conn.cursor()
cursor.execute("""
    SELECT tm.hs_code, tm.rate as duty_rate,
           (SELECT rate FROM tariff_measures
            WHERE hs_code = tm.hs_code AND tax_type='TVA' AND duty_type='MFN' LIMIT 1) AS vat_rate
    FROM tariff_measures tm
    WHERE tm.origin_country = 'TN' AND tm.duty_type = 'MFN' AND tm.tax_type = 'DD'
    ORDER BY tm.hs_code
""")
rows = cursor.fetchall()
conn.close()

DF_HS = pd.DataFrame(rows, columns=["hs_code","duty_rate","vat_rate"])

# Merge descriptions from scraped data
DF_HS = DF_HS.merge(df_mfn[["hs_code","description"]], on="hs_code", how="left")
DF_HS["description"] = DF_HS["description"].fillna("")

# Keep only actual tariff lines:
# - at least 6 digits (removes chapter headers like '01','02')
# - remove rows with no description
DF_HS = DF_HS[DF_HS["hs_code"].str.len() >= 6]
DF_HS = DF_HS[DF_HS["description"].str.len() > 0]

DF_HS["search_text"] = (DF_HS["description"] + " " + DF_HS["hs_code"]).str.lower()

print(f"✅ Loaded {len(DF_HS)} HS codes for dashboard.")
print(DF_HS[["hs_code","description","duty_rate"]].head(10))

async def capture_chapter_html():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        page = await browser.new_page()
        await page.goto(BASE_URL, wait_until="domcontentloaded", timeout=60000)
        await page.wait_for_timeout(5000)

        # Find nav frame and click first chapter
        nav_frame = None
        for f in page.frames:
            if "submit_frm_resultat" in await f.content():
                nav_frame = f
                break

        elements = await nav_frame.locator("a, input").all()
        for el in elements:
            onclick = await el.get_attribute("onclick") or ""
            if "submit_frm_resultat" in onclick:
                clean_js = onclick.replace("javascript:", "").strip()
                clean_js = re.sub(r"return\s+false\s*;?", "", clean_js).strip()
                if clean_js:
                    await nav_frame.evaluate(clean_js)
                    await page.wait_for_timeout(5000)
                    break

        # Dump all frame HTML to files
        for i, frame in enumerate(page.frames):
            html = await frame.content()
            if len(html) > 500:  # skip empty frames
                with open(f"frame_{i}.html", "w") as f:
                    f.write(html)
                print(f"frame_{i}.html — {len(html)} chars")

        await browser.close()

await capture_chapter_html()

import os
# Find the largest frame file — likely the results frame
files = [(os.path.getsize(f), f) for f in os.listdir() if f.startswith("frame_") and f.endswith(".html")]
files.sort(reverse=True)
print("Frame sizes:", files[:5])

# Show first 3000 chars of the largest one
with open(files[0][1]) as f:
    print(f.read(3000))

soup = BeautifulSoup(open("frame_0.html").read(), "lxml")

# Find all tables and show structure of first one that looks like tariff data
for i, table in enumerate(soup.find_all("table")):
    rows = table.find_all("tr")
    if len(rows) > 3:
        print(f"\n=== TABLE {i} ({len(rows)} rows) ===")
        # Show first 3 rows with all cell texts
        for tr in rows[:3]:
            cells = tr.find_all(["td","th"])
            print(f"  {len(cells)} cells: {[c.get_text(' ',strip=True)[:40] for c in cells]}")
        if i > 5:
            break

for i, table in enumerate(soup.find_all("table")):
    rows = table.find_all("tr")
    if len(rows) > 1:
        # Check max columns across all rows
        max_cols = max(len(tr.find_all(["td","th"])) for tr in rows)
        print(f"TABLE {i}: {len(rows)} rows, max {max_cols} cols")
        if max_cols > 3:
            # Show first 3 rows
            for tr in rows[:3]:
                cells = tr.find_all(["td","th"])
                print(f"  {[c.get_text(' ',strip=True)[:40] for c in cells]}")

async def capture_hs_detail():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        page = await browser.new_page()
        await page.goto(BASE_URL, wait_until="domcontentloaded", timeout=60000)
        await page.wait_for_timeout(5000)

        nav_frame = None
        for f in page.frames:
            if "submit_frm_resultat" in await f.content():
                nav_frame = f
                break

        # Click first chapter
        elements = await nav_frame.locator("a, input").all()
        for el in elements:
            onclick = await el.get_attribute("onclick") or ""
            if "submit_frm_resultat" in onclick:
                clean_js = onclick.replace("javascript:", "").strip()
                clean_js = re.sub(r"return\s+false\s*;?", "", clean_js).strip()
                if clean_js:
                    await nav_frame.evaluate(clean_js)
                    await page.wait_for_timeout(5000)
                    break

        # Now find and click the first HS code link in any frame
        for frame in page.frames:
            links = await frame.locator("a").all()
            for link in links:
                href = await link.get_attribute("href") or ""
                onclick = await link.get_attribute("onclick") or ""
                text = (await link.inner_text()).strip()
                # HS code links are typically numeric
                if re.match(r"^\d{6,}", text):
                    print(f"Clicking HS line: {text}")
                    try:
                        await link.click()
                        await page.wait_for_timeout(5000)
                        # Save all frames after click
                        for i, f2 in enumerate(page.frames):
                            html = await f2.content()
                            if len(html) > 500:
                                with open(f"detail_frame_{i}.html", "w") as fh:
                                    fh.write(html)
                                print(f"  detail_frame_{i}.html — {len(html)} chars")
                    except:
                        pass
                    break
            break

await capture_hs_detail()

import os
files = [(os.path.getsize(f), f) for f in os.listdir() if f.startswith("detail_frame_")]
files.sort(reverse=True)
print("Detail frame sizes:", files)

# Show tables in largest frame
with open(files[0][1]) as f:
    soup2 = BeautifulSoup(f.read(), "lxml")

for i, table in enumerate(soup2.find_all("table")):
    rows = table.find_all("tr")
    max_cols = max(len(tr.find_all(["td","th"])) for tr in rows) if rows else 0
    if max_cols > 2:
        print(f"\nTABLE {i}: {len(rows)} rows, max {max_cols} cols")
        for tr in rows[:5]:
            cells = tr.find_all(["td","th"])
            print(f"  {[c.get_text(' ',strip=True)[:50] for c in cells]}")

async def inspect_hs_links():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        page = await browser.new_page()
        await page.goto(BASE_URL, wait_until="domcontentloaded", timeout=60000)
        await page.wait_for_timeout(5000)

        nav_frame = None
        for f in page.frames:
            if "submit_frm_resultat" in await f.content():
                nav_frame = f
                break

        # Click first chapter
        elements = await nav_frame.locator("a, input").all()
        for el in elements:
            onclick = await el.get_attribute("onclick") or ""
            if "submit_frm_resultat" in onclick:
                clean_js = onclick.replace("javascript:", "").strip()
                clean_js = re.sub(r"return\s+false\s*;?", "", clean_js).strip()
                if clean_js:
                    await nav_frame.evaluate(clean_js)
                    await page.wait_for_timeout(5000)
                    break

        # Inspect ALL links and inputs across all frames after chapter click
        print("=== ALL CLICKABLE ELEMENTS ACROSS ALL FRAMES ===")
        for fi, frame in enumerate(page.frames):
            elements = await frame.locator("a, input[type=button], input[type=submit]").all()
            for el in elements[:20]:
                text = (await el.inner_text()).strip() if await el.get_attribute("type") != "submit" else ""
                onclick = await el.get_attribute("onclick") or ""
                href = await el.get_attribute("href") or ""
                if onclick or href:
                    print(f"  frame={fi} text='{text[:30]}' onclick='{onclick[:80]}' href='{href[:50]}'")

        await browser.close()

await inspect_hs_links()

async def inspect_frames():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        page = await browser.new_page()
        await page.goto(BASE_URL, wait_until="domcontentloaded", timeout=60000)
        await page.wait_for_timeout(8000)

        print("=== FRAMES BEFORE CHAPTER CLICK ===")
        for i, f in enumerate(page.frames):
            content = await f.content()
            print(f"  frame {i}: url={f.url} | len={len(content)}")

        # Find and click first chapter
        nav_frame = None
        for f in page.frames:
            content = await f.content()
            if "submit_frm_resultat" in content:
                nav_frame = f
                print(f"\nNav frame found: {f.url}")
                break

        if nav_frame:
            elements = await nav_frame.locator("a, input").all()
            for el in elements:
                onclick = await el.get_attribute("onclick") or ""
                if "submit_frm_resultat" in onclick:
                    clean_js = onclick.replace("javascript:", "").strip()
                    clean_js = re.sub(r"return\s+false\s*;?", "", clean_js).strip()
                    if clean_js:
                        print(f"Clicking: {clean_js[:80]}")
                        await nav_frame.evaluate(clean_js)
                        await page.wait_for_timeout(8000)
                        break

        print("\n=== FRAMES AFTER CHAPTER CLICK ===")
        for i, f in enumerate(page.frames):
            content = await f.content()
            print(f"  frame {i}: url={f.url} | len={len(content)}")

        await browser.close()

await inspect_frames()

async def capture_injected_content():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        page = await browser.new_page()
        await page.goto(BASE_URL, wait_until="domcontentloaded", timeout=60000)
        await page.wait_for_timeout(8000)

        nav_frame = None
        for f in page.frames:
            if "submit_frm_resultat" in await f.content():
                nav_frame = f
                break

        # Click first chapter
        elements = await nav_frame.locator("a, input").all()
        for el in elements:
            onclick = await el.get_attribute("onclick") or ""
            if "submit_frm_resultat" in onclick:
                clean_js = onclick.replace("javascript:", "").strip()
                clean_js = re.sub(r"return\s+false\s*;?", "", clean_js).strip()
                if clean_js:
                    await nav_frame.evaluate(clean_js)
                    await page.wait_for_timeout(8000)
                    break

        # Get the full page content and find the tariff section
        content = await page.content()
        soup = BeautifulSoup(content, "lxml")

        # Find all tables with more than 2 rows
        for i, table in enumerate(soup.find_all("table")):
            rows = table.find_all("tr")
            if len(rows) > 5:
                max_cols = max(len(tr.find_all(["td","th"])) for tr in rows)
                print(f"\nTABLE {i}: {len(rows)} rows, max {max_cols} cols")
                for tr in rows[:4]:
                    cells = tr.find_all(["td","th"])
                    print(f"  {[c.get_text(' ',strip=True)[:50] for c in cells]}")

        # Also look for any div/section that might contain tariff data
        print("\n=== DIVS WITH TARIFF-LIKE CONTENT ===")
        for div in soup.find_all(["div","section"]):
            text = div.get_text(" ", strip=True)
            if "DD" in text and "TVA" in text and len(text) > 100:
                print(f"  tag={div.name} id={div.get('id','')} class={div.get('class','')} len={len(text)}")
                print(f"  preview: {text[:200]}")
                break

        await browser.close()

await capture_injected_content()

async def capture_hs_detail():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        page = await browser.new_page()
        await page.goto(BASE_URL, wait_until="domcontentloaded", timeout=60000)
        await page.wait_for_timeout(8000)

        nav_frame = None
        for f in page.frames:
            if "submit_frm_resultat" in await f.content():
                nav_frame = f
                break

        # Click first chapter
        elements = await nav_frame.locator("a, input").all()
        for el in elements:
            onclick = await el.get_attribute("onclick") or ""
            if "submit_frm_resultat" in onclick:
                clean_js = onclick.replace("javascript:", "").strip()
                clean_js = re.sub(r"return\s+false\s*;?", "", clean_js).strip()
                if clean_js:
                    await nav_frame.evaluate(clean_js)
                    await page.wait_for_timeout(8000)
                    break

        # Find all links/inputs added after chapter click
        content_before = len(await page.content())
        print(f"Content length after chapter click: {content_before}")

        # Look for ALL onclick attributes in page that reference HS codes
        soup = BeautifulSoup(await page.content(), "lxml")
        print("\n=== ALL ONCLICK ATTRIBUTES IN PAGE ===")
        count = 0
        for el in soup.find_all(attrs={"onclick": True}):
            print(f"  tag={el.name} onclick='{el['onclick'][:100]}' text='{el.get_text(strip=True)[:30]}'")
            count += 1
            if count > 20:
                break

        # Also check for form elements
        print("\n=== ALL FORMS ===")
        for form in soup.find_all("form"):
            print(f"  form id={form.get('id','')} action={form.get('action','')} method={form.get('method','')}")
            for inp in form.find_all("input")[:5]:
                print(f"    input name={inp.get('name','')} type={inp.get('type','')} value={inp.get('value','')[:30]}")

        await browser.close()

await capture_hs_detail()

async def test_search_form():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        page = await browser.new_page()
        await page.goto(BASE_URL, wait_until="domcontentloaded", timeout=60000)
        await page.wait_for_timeout(8000)

        # Find and fill the mcle search input
        soup_before = BeautifulSoup(await page.content(), "lxml")
        print("Search form found:", bool(soup_before.find("input", {"name": "mcle"})))

        # Type an HS code into the search field and click search
        await page.fill("input[name='mcle']", "01012100015")
        await page.wait_for_timeout(1000)
        await page.click("input[value='🔍 Rechercher']")
        await page.wait_for_timeout(8000)

        # Check what changed
        content = await page.content()
        print(f"Content length after search: {len(content)}")

        soup = BeautifulSoup(content, "lxml")
        for i, table in enumerate(soup.find_all("table")):
            rows = table.find_all("tr")
            if len(rows) > 2:
                max_cols = max(len(tr.find_all(["td","th"])) for tr in rows)
                if max_cols > 2:
                    print(f"\nTABLE {i}: {len(rows)} rows, max {max_cols} cols")
                    for tr in rows[:5]:
                        cells = tr.find_all(["td","th"])
                        print(f"  {[c.get_text(' ',strip=True)[:50] for c in cells]}")

        # Save full page for inspection
        with open("search_result.html", "w") as f:
            f.write(content)
        print("\nSaved to search_result.html")

        await browser.close()

await test_search_form()

soup = BeautifulSoup(open("search_result.html").read(), "lxml")

# Show ALL tables regardless of column count
for i, table in enumerate(soup.find_all("table")):
    rows = table.find_all("tr")
    if len(rows) > 1:
        max_cols = max(len(tr.find_all(["td","th"])) for tr in rows)
        print(f"\nTABLE {i}: {len(rows)} rows, max {max_cols} cols")
        for tr in rows[:5]:
            cells = tr.find_all(["td","th"])
            print(f"  {[c.get_text(' ',strip=True)[:60] for c in cells]}")

# Also find any element containing "36" or "DD" near each other (duty rate clues)
print("\n=== TEXT BLOCKS CONTAINING DD AND % ===")
for el in soup.find_all(string=re.compile(r"DD|36\s*%|droit.*douane", re.I)):
    parent = el.parent
    text = parent.get_text(" ", strip=True)
    if len(text) > 20:
        print(f"  {text[:150]}")

async def intercept_requests():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        page = await browser.new_page()

        requests_log = []

        def on_request(request):
            if any(x in request.url for x in ["douane", "tarif", "ajax", "wp-admin"]):
                requests_log.append(f"REQ {request.method} {request.url}")

        def on_response(response):
            if any(x in response.url for x in ["douane", "tarif", "ajax", "wp-admin"]):
                requests_log.append(f"RES {response.status} {response.url}")

        page.on("request", on_request)
        page.on("response", on_response)

        await page.goto(BASE_URL, wait_until="domcontentloaded", timeout=60000)
        await page.wait_for_timeout(5000)

        print("=== REQUESTS ON PAGE LOAD ===")
        for r in requests_log:
            print(f"  {r}")
        requests_log.clear()

        # Click first chapter
        soup = BeautifulSoup(await page.content(), "lxml")
        nav_frame = page.frames[0]
        elements = await nav_frame.locator("a").all()
        for el in elements:
            onclick = await el.get_attribute("onclick") or ""
            if "submit_frm_resultat" in onclick:
                await nav_frame.evaluate(onclick.replace("javascript:","").replace("return false;","").strip())
                await page.wait_for_timeout(5000)
                break

        print("\n=== REQUESTS AFTER CHAPTER CLICK ===")
        for r in requests_log:
            print(f"  {r}")
        requests_log.clear()

        # Try clicking first HS code row in the table
        soup2 = BeautifulSoup(await page.content(), "lxml")
        table2 = soup2.find_all("table")[2] if len(soup2.find_all("table")) > 2 else None
        if table2:
            first_hs = table2.find_all("tr")[1].find("td").get_text(strip=True)
            print(f"\nTrying to click HS: {first_hs}")
            # Try filling search with this HS code
            await page.fill("input[name='mcle']", first_hs)
            await page.wait_for_timeout(500)
            await page.click("input[value='🔍 Rechercher']")
            await page.wait_for_timeout(5000)

        print("\n=== REQUESTS AFTER HS SEARCH ===")
        for r in requests_log:
            print(f"  {r}")

        await browser.close()

await intercept_requests()

import requests

# Fetch duty detail for one HS code
url = "https://www.douane.gov.tn/tarifwebnew/getresultat.php"
r = requests.get(url, params={"rech": "1", "mcle": "01012100015"})
print(f"Status: {r.status_code}")
print(f"Content length: {len(r.text)}")

soup = BeautifulSoup(r.text, "lxml")
for i, table in enumerate(soup.find_all("table")):
    rows = table.find_all("tr")
    if len(rows) > 1:
        max_cols = max(len(tr.find_all(["td","th"])) for tr in rows)
        print(f"\nTABLE {i}: {len(rows)} rows, max {max_cols} cols")
        for tr in rows[:8]:
            cells = tr.find_all(["td","th"])
            print(f"  {[c.get_text(' ',strip=True)[:60] for c in cells]}")

import requests

url = "https://www.douane.gov.tn/tarifwebnew/getresultat.php"
r = requests.get(url, params={"rech": "1", "mcle": "01012100015"}, verify=False)
print(f"Status: {r.status_code}")
print(f"Content length: {len(r.text)}")

soup = BeautifulSoup(r.text, "lxml")
for i, table in enumerate(soup.find_all("table")):
    rows = table.find_all("tr")
    if len(rows) > 1:
        max_cols = max(len(tr.find_all(["td","th"])) for tr in rows)
        print(f"\nTABLE {i}: {len(rows)} rows, max {max_cols} cols")
        for tr in rows[:8]:
            cells = tr.find_all(["td","th"])
            print(f"  {[c.get_text(' ',strip=True)[:60] for c in cells]}")

print(r.text)

url = "https://www.douane.gov.tn/tarifwebnew/getresultat.php"
r = requests.get(url, params={"choix": "", "chap": "", "nomen": "01012100015"}, verify=False)
print(f"Status: {r.status_code} | Length: {len(r.text)}")
print(r.text[:3000])

r = requests.get("https://www.douane.gov.tn/tarifwebnew/getresultat.php",
                  params={"choix": "", "chap": "", "nomen": "01012100015"},
                  verify=False)

# The 8MB response IS the full DB - let's search it for our HS code and nearby duty data
soup = BeautifulSoup(r.text, "lxml")

# Find the row for our HS code
for tr in soup.find_all("tr"):
    cells = tr.find_all(["td","th"])
    texts = [c.get_text(" ", strip=True) for c in cells]
    if any("01012100015" in t for t in texts):
        print(f"FOUND ROW: {texts}")
        # Print next 5 rows too
        next_rows = tr.find_next_siblings("tr", limit=5)
        for nr in next_rows:
            nc = nr.find_all(["td","th"])
            print(f"  NEXT: {[c.get_text(' ',strip=True)[:60] for c in nc]}")
        break

# Fetch the main JS bundle and find submit_frm_resultat
js_files = [
    "https://www.douane.gov.tn/wp-content/cache/minify/1/eb73d.js",
    "https://www.douane.gov.tn/wp-content/cache/minify/1/2056b.js",
    "https://www.douane.gov.tn/wp-content/cache/minify/1/3b869.js",
    "https://www.douane.gov.tn/wp-content/cache/minify/1/41005.js",
]

for js_url in js_files:
    r = requests.get(js_url, verify=False)
    if "submit_frm_resultat" in r.text:
        print(f"\nFOUND IN: {js_url}")
        # Find the function
        idx = r.text.find("submit_frm_resultat")
        print(r.text[max(0,idx-100):idx+500])
        break

js_files2 = [
    "https://www.douane.gov.tn/wp-content/cache/minify/1/32219.js",
    "https://www.douane.gov.tn/wp-content/cache/minify/1/30421.js",
    "https://www.douane.gov.tn/wp-content/cache/minify/1/ed5f4.js",
    "https://www.douane.gov.tn/wp-content/cache/minify/1/8d2a7.js",
    "https://www.douane.gov.tn/wp-content/cache/minify/1/df02c.js",
    "https://www.douane.gov.tn/wp-content/cache/minify/1/95d3e.js",
    "https://www.douane.gov.tn/wp-content/cache/minify/1/4b1b3.js",
    "https://www.douane.gov.tn/wp-content/cache/minify/1/b758e.js",
]

for js_url in js_files2:
    r = requests.get(js_url, verify=False)
    if "submit_frm_resultat" in r.text:
        print(f"\nFOUND IN: {js_url}")
        idx = r.text.find("submit_frm_resultat")
        print(r.text[max(0,idx-200):idx+600])
        break
else:
    print("Not found in any JS file - must be inline in the page HTML")
    # Search the main page
    r = requests.get("https://www.douane.gov.tn/tarifweb2025/", verify=False)
    idx = r.text.find("submit_frm_resultat")
    if idx > -1:
        print(f"FOUND IN MAIN PAGE:")
        print(r.text[max(0,idx-200):idx+600])

r = requests.get("https://www.douane.gov.tn/tarifweb2025/", verify=False)

# Find ALL occurrences of submit_frm_resultat
idx = 0
count = 0
while True:
    idx = r.text.find("function submit_frm_resultat", idx)
    if idx == -1:
        break
    print(f"\n=== OCCURRENCE {count+1} at position {idx} ===")
    print(r.text[idx:idx+800])
    idx += 100
    count += 1

idx = r.text.find("function submit_frm_resultat(str1, str2, str3)")
print(r.text[idx:idx+1500])

r = requests.get(
    "https://www.douane.gov.tn/tarifwebnew/getresultat.php",
    params={"choix": "", "chap": "", "sel": "01012100015"},
    verify=False
)
print(f"Status: {r.status_code} | Length: {len(r.text)}")

soup = BeautifulSoup(r.text, "lxml")
for i, table in enumerate(soup.find_all("table")):
    rows = table.find_all("tr")
    if len(rows) > 1:
        max_cols = max(len(tr.find_all(["td","th"])) for tr in rows)
        print(f"\nTABLE {i}: {len(rows)} rows, max {max_cols} cols")
        for tr in rows[:8]:
            cells = tr.find_all(["td","th"])
            print(f"  {[c.get_text(' ',strip=True)[:60] for c in cells]}")

import time

start = time.time()
r = requests.get(
    "https://www.douane.gov.tn/tarifwebnew/getresultat.php",
    params={"choix": "", "chap": "", "sel": "01012100015"},
    verify=False
)
elapsed = time.time() - start
print(f"Request time: {elapsed:.2f}s")
print(f"We have ~1023 HS codes")
print(f"Estimated total time at {elapsed:.2f}s each: {1023*elapsed/60:.1f} minutes")

conn = sqlite3.connect("tunisia_trade.db")
r = resolve_duty(conn, "01012100015", "TR")
print(r)
conn.close()

conn = sqlite3.connect("tunisia_trade.db")
cursor = conn.cursor()

# What's stored for this HS code?
cursor.execute("SELECT * FROM tariff_measures WHERE hs_code = '01012100015' LIMIT 10")
for r in cursor.fetchall():
    print(r)

print("\nAncestors generated:")
print(get_hs_ancestors("01012100015"))

print("\nDirect query:")
cursor.execute("""
    SELECT hs_code, origin_country, duty_type, rate
    FROM tariff_measures
    WHERE hs_code = '01012100015' AND tax_type = 'DD'
""")
for r in cursor.fetchall():
    print(r)

conn.close()

conn = sqlite3.connect("tunisia_trade.db")
conn.execute("""
    UPDATE tariff_measures SET valid_to = '2030-12-31'
""")
conn.commit()
conn.close()
print("✅ Validity dates updated")

conn = sqlite3.connect("tunisia_trade.db")
r = resolve_duty(conn, "01012100015", "TR")
print(r)
conn.close()

results_full = scrape_full(max_chapters=None, delay=0.3)

# Rebuild DB with full results
conn = sqlite3.connect("tunisia_trade.db")
cursor = conn.cursor()

cursor.execute("DROP TABLE IF EXISTS tariff_measures")
cursor.execute("DROP TABLE IF EXISTS hs_details")
cursor.execute("""
    CREATE TABLE tariff_measures (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        hs_code TEXT, origin_country TEXT, duty_type TEXT, tax_type TEXT,
        rate REAL, agreement_name TEXT, measure_type TEXT,
        valid_from DATE, valid_to DATE, assiette TEXT, tax_name TEXT
    )
""")
cursor.execute("""
    CREATE TABLE hs_details (
        hs_code TEXT PRIMARY KEY, description TEXT,
        import_regime TEXT, export_regime TEXT, other_taxes TEXT
    )
""")

for r in results_full:
    hs = r["hs_code"]
    cursor.execute("""
        INSERT INTO tariff_measures (hs_code, origin_country, duty_type, tax_type, rate, measure_type, valid_from, valid_to, assiette, tax_name)
        VALUES (?, 'TN', 'MFN', 'DD', ?, 'MFN', '2025-01-01', '2030-12-31', ?, 'DD')
    """, (hs, r["dd_rate"], r["dd_assiette"]))
    cursor.execute("""
        INSERT INTO tariff_measures (hs_code, origin_country, duty_type, tax_type, rate, measure_type, valid_from, valid_to, tax_name)
        VALUES (?, 'TN', 'MFN', 'TVA', ?, 'MFN', '2025-01-01', '2030-12-31', 'TVA')
    """, (hs, r["tva_rate"]))
    for tax in r.get("other_taxes", []):
        pct = re.findall(r"(\d+(?:\.\d+)?)\s*%", tax["value"])
        rate = float(pct[0]) if pct else None
        if rate is not None:
            cursor.execute("""
                INSERT INTO tariff_measures (hs_code, origin_country, duty_type, tax_type, rate, measure_type, valid_from, valid_to, assiette, tax_name)
                VALUES (?, 'TN', 'MFN', 'OTHER', ?, 'MFN', '2025-01-01', '2030-12-31', ?, ?)
            """, (hs, rate, tax["assiette"], tax["name"][:100]))
    for pref in r.get("pref_rates", []):
        iso2 = COUNTRY_CODE_MAP.get(pref["country_code"], pref["country_code"])
        cursor.execute("""
            INSERT INTO tariff_measures (hs_code, origin_country, duty_type, tax_type, rate, measure_type, valid_from, valid_to, tax_name)
            VALUES (?, ?, 'PREF', 'DD', ?, 'PREF', '2025-01-01', '2030-12-31', ?)
        """, (hs, iso2, pref["rate"], pref["country_name"][:100]))
    cursor.execute("""
        INSERT OR REPLACE INTO hs_details (hs_code, description, import_regime, export_regime, other_taxes)
        VALUES (?, ?, ?, ?, ?)
    """, (hs, r["description"], r["import_regime"], r["export_regime"], json.dumps(r["other_taxes"])))

conn.commit()

cursor.execute("SELECT COUNT(*) FROM tariff_measures WHERE duty_type='MFN' AND tax_type='DD'")
mfn = cursor.fetchone()[0]
cursor.execute("SELECT COUNT(*) FROM tariff_measures WHERE duty_type='PREF'")
pref = cursor.fetchone()[0]
cursor.execute("SELECT AVG(rate) FROM tariff_measures WHERE duty_type='MFN' AND tax_type='DD' AND rate > 0")
avg = cursor.fetchone()[0]
conn.close()

print(f"✅ {mfn} MFN rows | {pref} PREF rows | avg duty {avg:.1f}%")

ORIGIN_LABELS = {
    "CN": "China 🇨🇳", "TR": "Turkey 🇹🇷", "MA": "Morocco 🇲🇦", "EG": "Egypt 🇪🇬",
    "IT": "Italy 🇮🇹", "DE": "Germany 🇩🇪", "FR": "France 🇫🇷", "ES": "Spain 🇪🇸",
    "NL": "Netherlands 🇳🇱", "BE": "Belgium 🇧🇪", "IN": "India 🇮🇳", "US": "USA 🇺🇸",
    "JP": "Japan 🇯🇵", "KR": "S. Korea 🇰🇷", "VN": "Vietnam 🇻🇳", "BR": "Brazil 🇧🇷",
    "JO": "Jordan 🇯🇴", "SA": "Saudi Arabia 🇸🇦", "AE": "UAE 🇦🇪", "LY": "Libya 🇱🇾"
}
FREIGHT_FCL = {
    "CN":3800,"TR":850,"MA":700,"EG":900,"IT":900,"DE":1300,"FR":1100,
    "ES":800,"NL":1200,"BE":1200,"IN":2200,"US":4500,"JP":4000,"KR":3600,
    "VN":3200,"BR":5000,"JO":1100,"SA":1400,"AE":1600,"LY":600
}
LEAD_DAYS = {
    "CN":28,"TR":5,"MA":4,"EG":4,"IT":3,"DE":7,"FR":5,"ES":4,
    "NL":7,"BE":7,"IN":18,"US":18,"JP":32,"KR":30,"VN":26,
    "BR":22,"JO":6,"SA":8,"AE":10,"LY":3
}
USD_TO_TND = 3.12

def estimate_freight(origin, weight=500, volume=2.0):
    base = FREIGHT_FCL.get(origin, 2500)
    cbm = max(volume, weight/1000.0)
    if cbm >= 23: return float(base)
    elif cbm >= 1.0: return float(max(round(base / 33 * cbm * 1.3, 0), 200))
    else: return float(round(base * 0.1, 0))

def calc_landed(hs, origin, exw, weight=500, volume=2.0, incoterm="EXW", fodec=True, tcl=False):
    conn = sqlite3.connect("tunisia_trade.db")
    res = resolve_duty(conn, hs, origin)
    conn.close()
    duty_rate = res['rate'] if res['rate'] is not None else 0.0
    vat = float(DF_HS[DF_HS["hs_code"]==hs]["vat_rate"].iloc[0]) if not DF_HS[DF_HS["hs_code"]==hs].empty else 19.0
    if incoterm == "CIF": freight, cif = 0.0, exw
    elif incoterm == "FOB": freight = estimate_freight(origin, weight, volume)*0.7; cif = exw+freight
    else: freight = estimate_freight(origin, weight, volume); cif = exw+freight
    duty_amt = cif*(duty_rate/100)
    base = cif+duty_amt
    fodec_amt = base*0.01 if fodec else 0.0
    tcl_amt = (base+fodec_amt)*0.002 if tcl else 0.0
    vat_amt = (base+fodec_amt+tcl_amt)*(vat/100)
    landed = base+fodec_amt+tcl_amt+vat_amt
    return {
        "origin": origin, "agreement": res['duty_type'], "lead_days": LEAD_DAYS.get(origin,20),
        "exw": exw, "freight": round(freight,2), "cif": round(cif,2),
        "duty_rate": duty_rate, "duty_amt": round(duty_amt,2),
        "fodec": round(fodec_amt,2), "tcl": round(tcl_amt,2),
        "vat_rate": vat, "vat_amt": round(vat_amt,2),
        "landed": round(landed,2), "landed_tnd": round(landed*USD_TO_TND,2)
    }

def search_hs(query, limit=12):
    if not query.strip() or DF_HS.empty: return DF_HS.iloc[:0]
    hits = rfprocess.extract(query.lower(), DF_HS["search_text"].tolist(),
                              scorer=fuzz.partial_ratio, score_cutoff=30, limit=limit)
    if not hits: return DF_HS.iloc[:0]
    return DF_HS.iloc[[h[2] for h in hits]]

# Search panel
search_input = widgets.Text(placeholder="Type HS code...", layout=widgets.Layout(width="55%"))
search_btn = widgets.Button(description="Search", button_style="primary", icon="search", layout=widgets.Layout(width="100px"))
hs_dropdown = widgets.Dropdown(options=[], description="HS Code:", layout=widgets.Layout(width="100%"))
hs_info = widgets.Output()

def on_search(b):
    with hs_info: clear_output(wait=True)
    query = search_input.value.strip()
    if not query:
        hs_dropdown.options = [(f"{r['hs_code']}  —  {r['description'][:70]}", r["hs_code"])
                                for _, r in DF_HS.head(50).iterrows()]
        return
    results = search_hs(query)
    if results.empty:
        hs_dropdown.options = []
        with hs_info: print("No matches.")
        return
    hs_dropdown.options = [(f"{r['hs_code']}  —  {r['description'][:70]}", r["hs_code"])
                            for _, r in results.iterrows()]
    with hs_info: print(f"Found {len(results)} matches.")

def on_hs_change(change):
    hs = change["new"]
    if not hs: return
    row = DF_HS[DF_HS["hs_code"] == hs]
    if row.empty: return
    with hs_info:
        clear_output(wait=True)
        r = row.iloc[0]
        print(f"HS {r['hs_code']}  |  MFN Duty: {r['duty_rate']:.1f}%  |  VAT: {r['vat_rate']:.1f}%")

search_btn.on_click(on_search)
search_input.observe(lambda c: on_search(None) if len(c["new"])>2 else None, names="value")
hs_dropdown.observe(on_hs_change, names="value")
search_panel = widgets.VBox([
    widgets.HTML("<h4>🔍 Product Search</h4>"),
    widgets.HBox([search_input, search_btn]),
    hs_dropdown, hs_info
], layout=widgets.Layout(border="1px solid #555", padding="10px", margin="0 0 12px 0"))

# Sourcing tab
all_origins = sorted(ORIGIN_LABELS.keys())
exw_slider = widgets.FloatSlider(value=100, min=1, max=5000, step=10, description="EXW (USD):",
                                  style={'description_width':'initial'}, layout=widgets.Layout(width="60%"))
weight_input = widgets.FloatText(value=500, description="Weight (kg):", layout=widgets.Layout(width="200px"))
volume_input = widgets.FloatText(value=2.0, description="Volume (m³):", layout=widgets.Layout(width="200px"))
incoterm_dd = widgets.Dropdown(options=["EXW","FOB","CIF"], value="EXW", description="Incoterm:")
origin_selector = widgets.SelectMultiple(
    options=[(ORIGIN_LABELS[o], o) for o in all_origins],
    value=["CN","TR","MA","EG","IT"],
    description="Origins:",
    layout=widgets.Layout(height="160px", width="400px")
)
analyze_btn = widgets.Button(description="Analyze", button_style="success", icon="calculator")
sourcing_out = widgets.Output()

def on_analyze(b):
    with sourcing_out:
        clear_output(wait=True)
        hs = hs_dropdown.value
        if not hs: print("⚠️ Select an HS code first."); return
        results = [calc_landed(hs, o, exw_slider.value,
                               weight=weight_input.value,
                               volume=volume_input.value,
                               incoterm=incoterm_dd.value) for o in origin_selector.value]
        df_res = pd.DataFrame(results).sort_values("landed")
        display(df_res[["origin","agreement","duty_rate","freight","duty_amt","vat_amt","landed","landed_tnd","lead_days"]])
        fig = go.Figure(go.Bar(
            x=df_res["origin"], y=df_res["landed"],
            text=[f"${v:.0f}" for v in df_res["landed"]], textposition="auto",
            marker_color=["#2ecc71" if d==0 else "#e74c3c" for d in df_res["duty_rate"]]
        ))
        fig.update_layout(title=f"Landed Cost – HS {hs} ({incoterm_dd.value})", yaxis_title="USD", height=400)
        fig.show()

analyze_btn.on_click(on_analyze)
sourcing_tab = widgets.VBox([
    widgets.HBox([exw_slider]),
    widgets.HBox([weight_input, volume_input, incoterm_dd]),
    origin_selector,
    analyze_btn,
    sourcing_out
])

# Legal Paths tab
lp_origin = widgets.Dropdown(options=[(ORIGIN_LABELS[o], o) for o in all_origins], value="TR", description="Origin:")
lp_btn = widgets.Button(description="Resolve", button_style="primary")
lp_out = widgets.Output()

def on_lp(b):
    with lp_out:
        clear_output(wait=True)
        hs = hs_dropdown.value
        if not hs: print("⚠️ Select an HS code first."); return
        conn = sqlite3.connect("tunisia_trade.db")
        paths = enumerate_paths(conn, hs, lp_origin.value)
        conn.close()
        if not paths:
            print("No measures found for this HS + origin combination.")
            return
        df = pd.DataFrame(paths)[["rank","hs_code","origin_country","duty_type","rate","agreement_name","specificity"]]
        display(df)
        win = paths[0]
        print(f"\n✅ Winning measure: {win['agreement_name'] or win['duty_type']} — {win['duty_type']} at {win['rate']:.1f}%")

lp_btn.on_click(on_lp)
legal_tab = widgets.VBox([lp_origin, lp_btn, lp_out])

# Assemble
tabs = widgets.Tab([sourcing_tab, legal_tab])
tabs.set_title(0, "🌍 Sourcing")
tabs.set_title(1, "⚖️ Legal Paths")

display(widgets.VBox([
    widgets.HTML("<h2>🇹🇳 Tunisia Tariff Intelligence System</h2>"),
    search_panel,
    tabs
]))
print("✅ Dashboard ready.")